---
- name: install apache
  apt: name=apache2 state=present force=yes

- name: ensure apache started
  service: name=apache2 state=started enabled=yes

- name: enable mod_rewrite
  file:
    src: /etc/apache2/mods-available/rewrite.load
    dest: /etc/apache2/mods-enabled/rewrite.load
    state: link
  notify: restart apache

- name: create apache site docroot
  file:
    path:  "{{ apache_docroot }}"
    state: directory
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    mode:  0755
    recurse: yes

- name: configure apache site
  template:
    src: default.conf.j2
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache
