---
- name: add vb ppa
  lineinfile:
    path: /etc/apt/sources.list.d/virtualbox.list
    create: yes
    line: "deb http://download.virtualbox.org/virtualbox/debian {{ default_distro_codename }} contrib"
    state: present

- name: add public key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: add public key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: update cache
  shell: apt-get update

- name: install vb
  apt: name=virtualbox-5.1 state=latest
