---
- name: install gpg key
  apt_key:
    url: "https://download.sublimetext.com/sublimehq-pub.gpg"
    state: present

- name: add sublime text ppa
  apt_repository:
    repo: 'deb https://download.sublimetext.com/ apt/stable/'
    filename: sublime-text
    state: present

- name: update cache
  shell: apt-get update

- name: install sublime text
  apt: name="sublime-text" state=latest

