---
- name: add apt signing key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: add ppa
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

- name: update cache
  shell: apt-get update

- name: install docker-ce
  apt: name=docker-ce state=latest

- name: add {{ my_user }} to docker group
  user: name="{{ my_user }}" groups=docker append=yes
