---
- name: install linux common stuff
  apt: name="{{ item }}" state=present
  with_items:
  - apt-transport-https
  - build-essential
  - ca-certificates
  - gnupg2
  - "linux-headers-{{ ansible_kernel }}"
  - software-properties-common
  - sudo
