---
- name: install linux common stuff
  apt: name="{{ item }}" state=present
  with_items:
    - sudo
    - build-essential
    - software-properties-common
    - apt-transport-https
    - "linux-headers-{{ ansible_kernel }}"
