---
- name: add php ppa
  lineinfile:
    dest: /etc/apt/sources.list.d/php.list
    create: yes
    line: 'deb http://ppa.launchpad.net/ondrej/php/ubuntu trusty main'
    state: present

- name: update cache
  shell: apt-get update

- name: install php with extensions
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  with_items:
    - "php7.1"
    - "php7.1-bcmath"
    - "php7.1-bz2"
    - "php7.1-cgi"
    - "php7.1-cli"
    - "php7.1-common"
    - "php7.1-curl"
    - "php7.1-dev"
    - "php7.1-enchant"
    # - "php7.1-fpm" # Has unmet dependencies for Stretch
    # - "php7.1-gd" # Has unmet dependencies for Jessie
    - "php7.1-gmp"
    - "php7.1-imap"
    - "php7.1-interbase"
    # - "php7.1-intl" # Has unmet dependencies for Stretch
    - "php7.1-json"
    - "php7.1-ldap"
    - "php7.1-mbstring"
    - "php7.1-mcrypt"
    - "php7.1-mysql"
    - "php7.1-odbc"
    - "php7.1-pgsql"
    - "php7.1-phpdbg"
    - "php7.1-pspell"
    - "php7.1-readline"
    - "php7.1-recode"
    - "php7.1-soap"
    - "php7.1-sqlite3"
    - "php7.1-sybase"
    - "php7.1-tidy"
    - "php7.1-xml"
    - "php7.1-xmlrpc"
    - "php7.1-zip"
    - "libapache2-mod-php7.1"
    - 'php-xdebug'

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

- name: configure php
  template:
    src: php-dev.ini.j2
    dest: /etc/php/7.1/apache2/conf.d/php-dev.ini
    owner: root
    group: root
    mode: 0644

- name: configure apache php xdebug
  template:
    src: xdebug.ini.j2
    dest: /etc/php/7.1/apache2/conf.d/20-xdebug.ini
    owner: root
    group: root
    mode: 0644

- name: configure cli php xdebug
  template:
    src: xdebug.ini.j2
    dest: /etc/php/7.1/cli/conf.d/20-xdebug.ini
    owner: root
    group: root
    mode: 0644
